# Generated by Django 4.2.5 on 2023-10-06 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_category_designrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignRequest',
            new_name='CatalogRequest',
        ),
    ]
